# Generated by Django 5.0 on 2026-03-18 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_remove_num_recruiters_add_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='recruiters.recruiterregistration')),
            ],
            options={
                'db_table': 'recruiter_attendee',
                'ordering': ['order'],
            },
        ),
    ]
