# Generated by Django 5.0 on 2026-03-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_recruiter_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='boothpackage',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
    ]
