# Generated by Django 5.0 on 2026-04-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_curriculum'),
        ('recruiters', '0004_add_is_virtual_to_booth_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterregistration',
            name='recruiting_majors',
            field=models.ManyToManyField(blank=True, related_name='recruiter_registrations', to='accounts.curriculum'),
        ),
        migrations.AddField(
            model_name='recruiterregistration',
            name='recruiting_positions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
