# Generated by Django 5.0 on 2026-04-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0005_recruiting_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
