# Generated by Django 5.0 on 2026-04-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0006_add_payment_link_to_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterregistration',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
