# Generated by Django 5.0 on 2025-10-08 11:32

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('chapter', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StateProvince',
            fields=[
                ('st_id', models.IntegerField(primary_key=True, serialize=False)),
                ('st_name', models.CharField(max_length=50)),
                ('st_abbrev', models.CharField(max_length=5)),
                ('st_strtzip', models.CharField(blank=True, max_length=5)),
                ('st_endzip', models.CharField(blank=True, max_length=5)),
                ('st_region', models.CharField(blank=True, max_length=50)),
                ('st_conus', models.BooleanField(default=False)),
                ('st_foreign', models.BooleanField(default=False)),
                ('st_ctrid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'state_province',
                'ordering': ['st_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('alt_email', models.EmailField(blank=True, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounts.member')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_line1', models.CharField(max_length=255)),
                ('add_line2', models.CharField(blank=True, max_length=255)),
                ('add_city', models.CharField(max_length=100)),
                ('add_state', models.CharField(blank=True, max_length=100, null=True)),
                ('add_zip', models.CharField(blank=True, max_length=20)),
                ('add_country', models.CharField(default='United States', max_length=100)),
                ('add_type', models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('School', 'School')], max_length=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.member')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(default='+1', max_length=5)),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_type', models.CharField(choices=[('Mobile', 'Mobile'), ('Home', 'Home'), ('Work', 'Work')], max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='accounts.member')),
            ],
        ),
        migrations.CreateModel(
            name='UsedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_type', models.CharField(choices=[('activation', 'Account Activation'), ('password_reset', 'Password Reset')], max_length=20)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('member', 'add_type'), name='unique_member_address_type'),
        ),
        migrations.AddConstraint(
            model_name='phonenumbers',
            constraint=models.UniqueConstraint(fields=('member', 'phone_type'), name='unique_member_phone_type'),
        ),
        migrations.AddConstraint(
            model_name='phonenumbers',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('member',), name='unique_member_primary_phone'),
        ),
        migrations.AlterUniqueTogether(
            name='usedtoken',
            unique_together={('user', 'token_hash', 'token_type')},
        ),
    ]
