# Generated by Django 5.0 on 2025-10-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='phonenumbers',
            name='unique_member_primary_phone',
        ),
    ]
