# Generated by Django 5.0 on 2025-11-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_phonenumbers_unique_member_primary_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
