# Generated by Django 5.0 on 2026-02-27 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='date_of_birth',
            new_name='birth_date',
        ),
        migrations.AddField(
            model_name='person',
            name='initiation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='accounts.gender'),
        ),
    ]
