# Generated by Django 5.0 on 2026-03-16 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_date_of_birth_person_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pronoun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'pronoun',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.ForeignKey(blank=True, db_column='gender', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='accounts.gender'),
        ),
        migrations.AddField(
            model_name='person',
            name='pronoun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='accounts.pronoun'),
        ),
    ]
