# Generated by Django 5.0 on 2025-12-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_member_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('non-member', 'Non-Member'), ('collegiate', 'Collegiate'), ('alumni', 'Alumni'), ('official', 'Official')], default='non-member', max_length=20),
        ),
    ]
