# Generated by Django 5.0 on 2026-03-17 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pronoun_and_person_gender_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pronoun',
            field=models.ForeignKey(blank=True, db_column='pronoun', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='accounts.pronoun'),
        ),
    ]
