# Generated by Django 5.0 on 2025-12-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='preferred_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
