# Generated by Django 5.0 on 2026-04-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_pronoun_id_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('abbreviated', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'curriculum',
                'ordering': ['full_name'],
            },
        ),
    ]
