# Generated by Django 5.0 on 2025-12-16 15:16

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_address_is_primary_member_preferred_first_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='code',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='code',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='phonenumbers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonenumbers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='add_city',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='address',
            name='add_line1',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='member',
            name='chapter',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='phonenumbers',
            name='country_code',
            field=models.CharField(default='+1', max_length=5, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='phonenumbers',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='stateprovince',
            name='st_ctrid',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='usedtoken',
            name='token_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='alt_email',
            field=models.EmailField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['member', 'add_type'], name='accounts_ad_member__0c8621_idx'),
        ),
        migrations.AddIndex(
            model_name='code',
            index=models.Index(fields=['user'], name='accounts_co_user_id_b5097f_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_id'], name='accounts_me_member__71e926_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['chapter'], name='accounts_me_chapter_09f3eb_idx'),
        ),
        migrations.AddIndex(
            model_name='phonenumbers',
            index=models.Index(fields=['member', 'phone_type'], name='accounts_ph_member__fc686c_idx'),
        ),
        migrations.AddIndex(
            model_name='phonenumbers',
            index=models.Index(fields=['member', 'is_primary'], name='accounts_ph_member__c74f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='stateprovince',
            index=models.Index(fields=['st_ctrid'], name='state_provi_st_ctri_e0aeff_idx'),
        ),
        migrations.AddIndex(
            model_name='stateprovince',
            index=models.Index(fields=['st_abbrev'], name='state_provi_st_abbr_8ec352_idx'),
        ),
        migrations.AddIndex(
            model_name='usedtoken',
            index=models.Index(fields=['user', 'token_type'], name='accounts_us_user_id_1f260a_idx'),
        ),
        migrations.AddIndex(
            model_name='usedtoken',
            index=models.Index(fields=['token_hash'], name='accounts_us_token_h_3013cd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='accounts_us_is_acti_a5841d_idx'),
        ),
    ]
