# Generated by Django 5.0 on 2026-04-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_curriculum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='initiation_date',
        ),
        migrations.AddField(
            model_name='member',
            name='initiation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
