# Generated by Django 5.0 on 2025-12-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_options_address_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='address',
            name='accounts_ad_member__0c8621_idx',
        ),
        migrations.RemoveIndex(
            model_name='code',
            name='accounts_co_user_id_b5097f_idx',
        ),
        migrations.RemoveIndex(
            model_name='member',
            name='accounts_me_member__71e926_idx',
        ),
        migrations.RemoveIndex(
            model_name='member',
            name='accounts_me_chapter_09f3eb_idx',
        ),
        migrations.RemoveIndex(
            model_name='phonenumbers',
            name='accounts_ph_member__fc686c_idx',
        ),
        migrations.RemoveIndex(
            model_name='phonenumbers',
            name='accounts_ph_member__c74f6d_idx',
        ),
        migrations.RemoveIndex(
            model_name='stateprovince',
            name='state_provi_st_ctri_e0aeff_idx',
        ),
        migrations.RemoveIndex(
            model_name='stateprovince',
            name='state_provi_st_abbr_8ec352_idx',
        ),
        migrations.RemoveIndex(
            model_name='usedtoken',
            name='accounts_us_user_id_1f260a_idx',
        ),
        migrations.RemoveIndex(
            model_name='usedtoken',
            name='accounts_us_token_h_3013cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_email_74c8d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_is_acti_a5841d_idx',
        ),
        migrations.RemoveField(
            model_name='address',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='address',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='code',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='code',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='phonenumbers',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='phonenumbers',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='address',
            name='add_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='add_line1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='chapter',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='phonenumbers',
            name='country_code',
            field=models.CharField(default='+1', max_length=5),
        ),
        migrations.AlterField(
            model_name='phonenumbers',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stateprovince',
            name='st_ctrid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usedtoken',
            name='token_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='alt_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
