# Generated by Django 5.0 on 2026-04-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_person_initiation_date_member_initiation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='chapter',
            new_name='chapter_code',
        ),
    ]
