# Generated by Django 5.0 on 2026-04-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_chapter_member_chapter_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='member',
            name='resume_uploaded_at',
        ),
    ]
