# Generated by Django 5.0 on 2026-01-27 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='User',
            table='users',
        ),
    ]
