# Generated by Django 5.0 on 2026-04-14 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_ethnicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ethnicity',
            field=models.ForeignKey(blank=True, db_column='ethnicity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='accounts.ethnicity'),
        ),
    ]
