# Generated by Django 5.0 on 2026-01-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_user_table'),
    ]

    operations = [
         migrations.AlterModelTable(
            name='User',
            table='user',
        ),
    ]
