# Generated by Django 5.0 on 2026-04-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_curriculum_to_resumecurriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='school_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
