# Generated by Django 5.0 on 2026-01-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoneNumbers',
            new_name='PhoneNumber',
        ),
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AlterModelTable(
            name='code',
            table='two_factor_code',
        ),
        migrations.AlterModelTable(
            name='member',
            table='member',
        ),
        migrations.AlterModelTable(
            name='phonenumber',
            table='phone_number',
        ),
        migrations.AlterModelTable(
            name='usedtoken',
            table='used_token',
        ),
    ]
