# Generated by Django 5.0 on 2026-01-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_phonenumbers_phonenumber_alter_address_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='member',
            name='district',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
