# Generated by Django 5.0 on 2026-05-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_member_school_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
