# Generated by Django 5.0 on 2026-02-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_create_role_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='member',
            name='resume_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('member', 'Member'), ('recruiter', 'Recruiter')], default='member', max_length=20),
        ),
    ]
