# Generated by Django 5.0 on 2026-01-08 17:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_alter_user_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(help_text='Chapter name or code', max_length=100)),
                ('report_date', models.DateField(help_text='Date of the event/trip')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('check', 'Check'), ('direct_deposit', 'Direct Deposit'), ('credit', 'Credit to Account'), ('other', 'Other')], max_length=20)),
                ('payment_check_number', models.CharField(blank=True, max_length=50)),
                ('payment_payer', models.CharField(blank=True, max_length=200)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('verified_by_member', models.BooleanField(default=False)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('validation_code', models.CharField(blank=True, max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total reimbursement amount', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expense_reports', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_reports', to='accounts.member')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_expense_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseReportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automobile_miles', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('automobile_tolls', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('passengers', models.IntegerField(default=0, help_text='Number of passengers (not including driver)', validators=[django.core.validators.MinValueValidator(0)])),
                ('lodging_nights', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('lodging_per_night', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual cost per night', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('breakfast_enroute', models.IntegerField(default=0, help_text='Number of breakfasts en route', validators=[django.core.validators.MinValueValidator(0)])),
                ('lunch_enroute', models.IntegerField(default=0, help_text='Number of lunches en route', validators=[django.core.validators.MinValueValidator(0)])),
                ('dinner_enroute', models.IntegerField(default=0, help_text='Number of dinners en route', validators=[django.core.validators.MinValueValidator(0)])),
                ('breakfast_onsite', models.IntegerField(default=0, help_text='Number of breakfasts at convention', validators=[django.core.validators.MinValueValidator(0)])),
                ('lunch_onsite', models.IntegerField(default=0, help_text='Number of lunches at convention', validators=[django.core.validators.MinValueValidator(0)])),
                ('terminal_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Airport parking, etc.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('public_carrier_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Airline, train, bus, etc.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('other_onsite_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Other on-site expenses', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('billed_to_hq', models.BooleanField(default=False, help_text='Was this billed directly to headquarters?')),
                ('expense_notes', models.TextField(blank=True, help_text='Additional notes about expenses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='expense_reports.expensereport')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_code', models.CharField(max_length=5, unique=True)),
                ('report_name', models.CharField(max_length=200)),
                ('implemented', models.BooleanField(default=True)),
                ('update_board', models.BooleanField(default=False)),
                ('mileage_rate', models.DecimalField(decimal_places=2, default=Decimal('0.25'), help_text='Rate per mile for automobile', max_digits=5)),
                ('max_passengers', models.IntegerField(default=3)),
                ('passenger_mileage_rate', models.DecimalField(decimal_places=2, default=Decimal('0.05'), help_text='Additional rate per mile per passenger', max_digits=5)),
                ('max_lodging_per_night', models.DecimalField(decimal_places=2, default=Decimal('42.00'), help_text='Maximum reimbursement per night', max_digits=7)),
                ('max_breakfast_daily', models.DecimalField(decimal_places=2, default=Decimal('6.00'), max_digits=5)),
                ('max_lunch_daily', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5)),
                ('max_dinner_daily', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('max_breakfast_onsite', models.DecimalField(decimal_places=2, default=Decimal('9.00'), max_digits=5)),
                ('max_lunch_onsite', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('daily_meal_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total daily meal limit (0 = no limit)', max_digits=5)),
                ('description', models.TextField(blank=True, help_text='Description of this report type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['report_code'],
                'indexes': [models.Index(fields=['report_code'], name='expense_rep_report__3bf6fe_idx'), models.Index(fields=['implemented'], name='expense_rep_impleme_3dc43b_idx')],
            },
        ),
        migrations.AddField(
            model_name='expensereport',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_reports', to='expense_reports.expensereporttype'),
        ),
        migrations.AddIndex(
            model_name='expensereport',
            index=models.Index(fields=['member', 'status'], name='expense_rep_member__292707_idx'),
        ),
        migrations.AddIndex(
            model_name='expensereport',
            index=models.Index(fields=['status', 'created_at'], name='expense_rep_status_5ec5e7_idx'),
        ),
        migrations.AddIndex(
            model_name='expensereport',
            index=models.Index(fields=['report_date'], name='expense_rep_report__5b0e49_idx'),
        ),
    ]
