# Generated by Django 5.0 on 2026-04-28 21:31

import expense_reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensereport',
            name='receipt',
            field=models.FileField(blank=True, help_text='Combined PDF of all receipt images', null=True, upload_to=expense_reports.models.receipt_upload_path),
        ),
    ]
