# Generated by Django 5.0 on 2026-01-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expensereporttype',
            name='expense_rep_impleme_3dc43b_idx',
        ),
        migrations.RenameField(
            model_name='expensereporttype',
            old_name='implemented',
            new_name='is_active',
        ),
        migrations.AddIndex(
            model_name='expensereporttype',
            index=models.Index(fields=['is_active'], name='expense_rep_is_acti_078bfe_idx'),
        ),
    ]
