# Generated by Django 5.0 on 2026-01-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_reports', '0002_remove_expensereporttype_expense_rep_impleme_3dc43b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensereport',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
