# Generated by Django 5.0 on 2026-01-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_reports', '0003_alter_expensereport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereport',
            name='receipt',
            field=models.FileField(blank=True, help_text='Combined PDF of all receipt images', null=True, upload_to='receipts/'),
        ),
    ]
