# Generated by Django 5.0 on 2026-01-21 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_managers'),
        ('expense_reports', '0004_expensereport_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereport',
            name='mailing_address',
            field=models.ForeignKey(default=1, help_text='Address where check should be mailed', on_delete=django.db.models.deletion.PROTECT, related_name='expense_reports', to='accounts.address'),
            preserve_default=False,
        ),
    ]
