# Generated by Django 5.0 on 2026-01-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_reports', '0005_expensereport_mailing_address'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expensereport',
            new_name='expense_rep_member__004c44_idx',
            old_name='expense_rep_member__292707_idx',
        ),
        migrations.RenameIndex(
            model_name='expensereport',
            new_name='expense_rep_status_826999_idx',
            old_name='expense_rep_status_5ec5e7_idx',
        ),
        migrations.RenameIndex(
            model_name='expensereport',
            new_name='expense_rep_report__bf4b97_idx',
            old_name='expense_rep_report__5b0e49_idx',
        ),
        migrations.RenameIndex(
            model_name='expensereporttype',
            new_name='expense_rep_report__08c0fd_idx',
            old_name='expense_rep_report__3bf6fe_idx',
        ),
        migrations.RenameIndex(
            model_name='expensereporttype',
            new_name='expense_rep_is_acti_034cd8_idx',
            old_name='expense_rep_is_acti_078bfe_idx',
        ),
        migrations.AlterModelTable(
            name='expensereport',
            table='expense_report',
        ),
        migrations.AlterModelTable(
            name='expensereportdetail',
            table='expense_report_detail',
        ),
        migrations.AlterModelTable(
            name='expensereporttype',
            table='expense_report_type',
        ),
    ]
