# Generated by Django 5.0 on 2026-02-20 14:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_reports', '0006_rename_expense_rep_member__292707_idx_expense_rep_member__004c44_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensereportdetail',
            name='automobile_miles',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99999.99'))]),
        ),
        migrations.AlterField(
            model_name='expensereportdetail',
            name='automobile_tolls',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999.99'))]),
        ),
        migrations.AlterField(
            model_name='expensereportdetail',
            name='breakfast_enroute',
            field=models.IntegerField(default=0, help_text='Number of breakfasts en route', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='expensereportdetail',
            name='breakfast_onsite',
            field=models.IntegerField(default=0, help_text='Number of breakfasts at convention', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='expensereportdetail',
            name='dinner_enroute',
            field=models.IntegerField(default=0, help_text='Number of dinners en route', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='expensereportdetail',
            name='lodging_nights',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='expensereportdetail',
            name='lodging_per_night',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual cost per night', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999.99'))]),
        ),
        migrations.AlterField(
            model_name='expensereportdetail',
            name='lunch_enroute',
            field=models.IntegerField(default=0, help_text='Number of lunches en route', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='expensereportdetail',
            name='lunch_onsite',
            field=models.IntegerField(default=0, help_text='Number of lunches at convention', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='expensereportdetail',
            name='other_onsite_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Other on-site expenses', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999.99'))]),
        ),
        migrations.AlterField(
            model_name='expensereportdetail',
            name='passengers',
            field=models.IntegerField(default=0, help_text='Number of passengers (not including driver)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='expensereportdetail',
            name='public_carrier_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Airline, train, bus, etc.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99999.99'))]),
        ),
        migrations.AlterField(
            model_name='expensereportdetail',
            name='terminal_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Airport parking, etc.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999.99'))]),
        ),
    ]
