# Generated by Django 5.0 on 2026-02-26 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('checkbox', 'Checkbox'), ('true_false', 'True / False'), ('yes_no', 'Yes / No'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('rating', 'Rating'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('rating_min', models.IntegerField(blank=True, default=1, null=True)),
                ('rating_max', models.IntegerField(blank=True, default=5, null=True)),
                ('rating_min_label', models.CharField(blank=True, max_length=100)),
                ('rating_max_label', models.CharField(blank=True, max_length=100)),
                ('has_correct_answer', models.BooleanField(default=False)),
                ('points', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'survey_question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('choice_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='surveys.question')),
            ],
            options={
                'db_table': 'survey_question_choice',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('survey_type', models.CharField(choices=[('survey', 'Survey'), ('questionnaire', 'Questionnaire'), ('test', 'Test'), ('quiz', 'Quiz'), ('assessment', 'Assessment')], default='survey', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('allow_multiple_submissions', models.BooleanField(default=False)),
                ('is_graded', models.BooleanField(default=False)),
                ('passing_score', models.IntegerField(blank=True, help_text='Passing percentage (0–100). Only used when is_graded=True.', null=True)),
                ('open_date', models.DateTimeField(blank=True, help_text='Null = always open', null=True)),
                ('close_date', models.DateTimeField(blank=True, help_text='Null = no end date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'survey',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey'),
        ),
        migrations.CreateModel(
            name='SurveyAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_type', models.CharField(choices=[('open', 'Open'), ('role', 'Role'), ('user', 'User')], max_length=10)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience', to='surveys.survey')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_audience_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'survey_audience',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('total_possible_points', models.IntegerField(blank=True, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'survey_response',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('number_answer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_answer', models.DateField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.question')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='answers', to='surveys.questionchoice')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyresponse')),
            ],
            options={
                'db_table': 'survey_answer',
            },
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['is_active'], name='survey_is_acti_a3dc23_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['created_at'], name='survey_created_7eef63_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['survey', 'user'], name='survey_resp_survey__888f85_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['is_complete'], name='survey_resp_is_comp_93ab71_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('response', 'question')},
        ),
    ]
