# Generated by Django 5.0 on 2026-02-26 20:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'airport',
                'ordering': ['state', 'description'],
                'indexes': [models.Index(fields=['state'], name='airport_state_fbb255_idx')],
            },
        ),
        migrations.CreateModel(
            name='Convention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_open_date', models.DateField(blank=True, null=True)),
                ('registration_close_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'convention',
                'ordering': ['-year', '-start_date'],
                'indexes': [models.Index(fields=['year'], name='convention_year_78f9ab_idx'), models.Index(fields=['is_active'], name='convention_is_acti_dcc2fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConventionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_guest', models.BooleanField(default=False)),
                ('status_code', models.CharField(choices=[('registered', 'Registered'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('checked_in', 'Checked In'), ('waitlisted', 'Waitlisted')], default='registered', max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('credentials_received', models.BooleanField(default=False)),
                ('credentials_received_date', models.DateTimeField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('at_convention', models.BooleanField(default=False)),
                ('visible_to_recruiters', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='convention.convention')),
                ('host_registration', models.ForeignKey(blank=True, help_text="Only populated if is_guest=True. References the host's registration.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='convention.conventionregistration')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convention_registrations', to='accounts.person')),
            ],
            options={
                'db_table': 'convention_registration',
            },
        ),
        migrations.CreateModel(
            name='ConventionGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_first_name', models.CharField(max_length=100)),
                ('guest_last_name', models.CharField(max_length=100)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('guest_dietary_restrictions', models.TextField(blank=True)),
                ('guest_special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_details', to='convention.conventionregistration')),
            ],
            options={
                'db_table': 'convention_guest',
            },
        ),
        migrations.CreateModel(
            name='ConventionCommitteePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumni_affairs', models.IntegerField(choices=[(0, 'No Interest'), (1, 'Interested'), (2, 'Prefer')], default=0)),
                ('awards', models.IntegerField(choices=[(0, 'No Interest'), (1, 'Interested'), (2, 'Prefer')], default=0)),
                ('chapter_operations', models.IntegerField(choices=[(0, 'No Interest'), (1, 'Interested'), (2, 'Prefer')], default=0)),
                ('collegiate_chapters', models.IntegerField(choices=[(0, 'No Interest'), (1, 'Interested'), (2, 'Prefer')], default=0)),
                ('communications', models.IntegerField(choices=[(0, 'No Interest'), (1, 'Interested'), (2, 'Prefer')], default=0)),
                ('constitution', models.IntegerField(choices=[(0, 'No Interest'), (1, 'Interested'), (2, 'Prefer')], default=0)),
                ('engineering_futures', models.IntegerField(choices=[(0, 'No Interest'), (1, 'Interested'), (2, 'Prefer')], default=0)),
                ('membership', models.IntegerField(choices=[(0, 'No Interest'), (1, 'Interested'), (2, 'Prefer')], default=0)),
                ('public_relations', models.IntegerField(choices=[(0, 'No Interest'), (1, 'Interested'), (2, 'Prefer')], default=0)),
                ('resolutions', models.IntegerField(choices=[(0, 'No Interest'), (1, 'Interested'), (2, 'Prefer')], default=0)),
                ('rituals', models.IntegerField(choices=[(0, 'No Interest'), (1, 'Interested'), (2, 'Prefer')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='committee_preferences', to='convention.conventionregistration')),
            ],
            options={
                'db_table': 'convention_committee_preference',
            },
        ),
        migrations.CreateModel(
            name='ConventionAccommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_choice', models.CharField(choices=[('full', 'Full Package - All meals and events'), ('partial', 'Partial Package - Select meals'), ('commuter', 'Commuter Package - No hotel'), ('custom', 'Custom Package')], default='full', max_length=20)),
                ('needs_hotel', models.BooleanField(default=True)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('roommate_preference', models.CharField(choices=[('single', 'Single Room'), ('specific', 'Specific Roommate'), ('any', 'Any Roommate')], default='any', max_length=20)),
                ('specific_roommate_name', models.CharField(blank=True, max_length=200)),
                ('specific_roommate_chapter', models.CharField(blank=True, max_length=100)),
                ('food_allergies', models.TextField(blank=True)),
                ('dietary_restrictions', models.TextField(blank=True)),
                ('other_allergies', models.TextField(blank=True)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('room_confirmation', models.CharField(blank=True, max_length=50)),
                ('special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation', to='convention.conventionregistration')),
            ],
            options={
                'db_table': 'convention_accomodation',
            },
        ),
        migrations.CreateModel(
            name='ConventionTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_method', models.CharField(choices=[('driving', 'Driving'), ('self_booking', 'Booking Own Flight'), ('need_booking', 'Need Flight Booked')], default='need_booking', max_length=20)),
                ('departure_airport', models.CharField(blank=True, help_text='3-letter airport code', max_length=3)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('departure_time_preference', models.IntegerField(blank=True, help_text='Minutes from midnight (0-1410)', null=True)),
                ('return_airport', models.CharField(blank=True, help_text='3-letter airport code', max_length=3)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_time_preference', models.IntegerField(blank=True, help_text='Minutes from midnight (0-1410)', null=True)),
                ('seat_preference', models.CharField(choices=[('none', 'No Preference'), ('window', 'Window'), ('aisle', 'Aisle')], default='none', max_length=10)),
                ('needs_ground_transportation', models.BooleanField(default=True, help_text='Whether member needs transportation to/from convention airport')),
                ('outbound_airline', models.CharField(blank=True, max_length=100)),
                ('outbound_flight_number', models.CharField(blank=True, max_length=20)),
                ('outbound_departure_time', models.DateTimeField(blank=True, null=True)),
                ('outbound_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('outbound_confirmation', models.CharField(blank=True, max_length=50)),
                ('return_airline', models.CharField(blank=True, max_length=100)),
                ('return_flight_number', models.CharField(blank=True, max_length=20)),
                ('return_departure_time', models.DateTimeField(blank=True, null=True)),
                ('return_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('return_confirmation', models.CharField(blank=True, max_length=50)),
                ('flight_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel', to='convention.conventionregistration')),
            ],
            options={
                'db_table': 'convention_travel_plan',
            },
        ),
        migrations.AddIndex(
            model_name='conventionregistration',
            index=models.Index(fields=['convention', 'is_guest'], name='convention__convent_c9df87_idx'),
        ),
        migrations.AddIndex(
            model_name='conventionregistration',
            index=models.Index(fields=['host_registration'], name='convention__host_re_b59c93_idx'),
        ),
        migrations.AddIndex(
            model_name='conventionregistration',
            index=models.Index(fields=['status_code'], name='convention__status__2ce37a_idx'),
        ),
        migrations.AddConstraint(
            model_name='conventionregistration',
            constraint=models.UniqueConstraint(fields=('convention', 'person'), name='unique_convention_person'),
        ),
    ]
