# Generated by Django 5.0 on 2025-12-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convention', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventioncommitteepreference',
            name='public_relations',
            field=models.IntegerField(choices=[(0, 'No Interest'), (1, 'Interested'), (2, 'Prefer')], default=0),
        ),
        migrations.AddField(
            model_name='conventioncommitteepreference',
            name='resolutions',
            field=models.IntegerField(choices=[(0, 'No Interest'), (1, 'Interested'), (2, 'Prefer')], default=0),
        ),
        migrations.AddField(
            model_name='conventioncommitteepreference',
            name='rituals',
            field=models.IntegerField(choices=[(0, 'No Interest'), (1, 'Interested'), (2, 'Prefer')], default=0),
        ),
    ]
