# Generated by Django 5.0 on 2026-02-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convention', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventionregistration',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
