# Generated by Django 5.0 on 2025-12-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convention', '0002_conventioncommitteepreference_public_relations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventiontravel',
            name='needs_ground_transportation',
            field=models.BooleanField(default=True, help_text='Whether member needs transportation to/from convention airport'),
        ),
        migrations.AddField(
            model_name='conventiontravel',
            name='seat_preference',
            field=models.CharField(choices=[('none', 'No Preference'), ('window', 'Window'), ('aisle', 'Aisle')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='conventiontravel',
            name='departure_airport',
            field=models.CharField(blank=True, help_text='3-letter airport code', max_length=3),
        ),
        migrations.AlterField(
            model_name='conventiontravel',
            name='departure_time_preference',
            field=models.IntegerField(blank=True, help_text='Minutes from midnight (0-1410)', null=True),
        ),
        migrations.AlterField(
            model_name='conventiontravel',
            name='return_airport',
            field=models.CharField(blank=True, help_text='3-letter airport code', max_length=3),
        ),
        migrations.AlterField(
            model_name='conventiontravel',
            name='return_time_preference',
            field=models.IntegerField(blank=True, help_text='Minutes from midnight (0-1410)', null=True),
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['state', 'description'],
                'indexes': [models.Index(fields=['state'], name='convention__state_216214_idx')],
            },
        ),
    ]
