# Generated by Django 5.0 on 2026-01-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convention', '0003_conventiontravel_needs_ground_transportation_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='airport',
            new_name='airport_state_fbb255_idx',
            old_name='convention__state_216214_idx',
        ),
        migrations.RenameIndex(
            model_name='convention',
            new_name='convention_year_78f9ab_idx',
            old_name='convention__year_94b04c_idx',
        ),
        migrations.RenameIndex(
            model_name='convention',
            new_name='convention_is_acti_dcc2fe_idx',
            old_name='convention__is_acti_1bfff8_idx',
        ),
        migrations.RenameIndex(
            model_name='conventionregistration',
            new_name='convention__convent_c9df87_idx',
            old_name='convention__convent_d5982f_idx',
        ),
        migrations.RenameIndex(
            model_name='conventionregistration',
            new_name='convention__host_re_b59c93_idx',
            old_name='convention__host_re_47aba2_idx',
        ),
        migrations.RenameIndex(
            model_name='conventionregistration',
            new_name='convention__status__2ce37a_idx',
            old_name='convention__status__ffa922_idx',
        ),
        migrations.AlterModelTable(
            name='airport',
            table='airport',
        ),
        migrations.AlterModelTable(
            name='convention',
            table='convention',
        ),
        migrations.AlterModelTable(
            name='conventionaccommodation',
            table='convention_accomodation',
        ),
        migrations.AlterModelTable(
            name='conventioncommitteepreference',
            table='convention_committee_preference',
        ),
        migrations.AlterModelTable(
            name='conventionguest',
            table='convention_guest',
        ),
        migrations.AlterModelTable(
            name='conventionregistration',
            table='convention_registration',
        ),
        migrations.AlterModelTable(
            name='conventiontravel',
            table='convention_travel_plan',
        ),
    ]
