# Generated by Django 5.0 on 2026-02-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convention', '0004_rename_convention__state_216214_idx_airport_state_fbb255_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventionregistration',
            name='visible_to_recruiters',
            field=models.BooleanField(default=True),
        ),
    ]
