# Generated by Django 5.0 on 2026-04-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convention', '0007_conventionregistration_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventionregistration',
            name='guest_attending',
            field=models.BooleanField(blank=True, default=None, help_text='Null=undecided, False=not bringing a guest, True=bringing a guest', null=True),
        ),
    ]
