# Generated by Django 5.0 on 2026-04-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_curriculum_to_resumecurriculum'),
        ('convention', '0009_conventionregistration_resume_curriculum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conventionregistration',
            name='resume_curriculum',
        ),
        migrations.AddField(
            model_name='conventionregistration',
            name='resume_curricula',
            field=models.ManyToManyField(blank=True, related_name='resume_registrations', to='accounts.resumecurriculum'),
        ),
    ]
