# Generated by Django 5.0 on 2026-04-28 21:31

import convention.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convention', '0010_conventionregistration_resume_curricula_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conventionregistration',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=convention.models.resume_upload_path),
        ),
    ]
