# Generated by Django 5.0 on 2026-05-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convention', '0012_convention_convention_series_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convention',
            name='convention_series',
        ),
    ]
