# Generated by Django 5.0 on 2026-05-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convention', '0013_remove_convention_convention_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventiontravel',
            name='travel_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
