# Generated by Django 5.0 on 2026-05-14 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convention', '0014_conventiontravel_travel_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventionregistration',
            name='contact_email',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='conventionregistration',
            name='terms_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conventionregistration',
            name='terms_agreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConventionTermsToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms_token', to='convention.conventionregistration')),
            ],
            options={
                'db_table': 'convention_terms_token',
            },
        ),
    ]
