# Generated by Django 5.0 on 2026-05-14 19:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convention', '0015_conventionregistration_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConventionFullyPaidChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_code', models.CharField(db_index=True, max_length=10)),
                ('spots_available', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('spots_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fully_paid_chapters', to='convention.convention')),
            ],
            options={
                'db_table': 'convention_fully_paid_chapters',
            },
        ),
        migrations.AddConstraint(
            model_name='conventionfullypaidchapter',
            constraint=models.UniqueConstraint(fields=('convention', 'chapter_code'), name='unique_chapter_per_convention'),
        ),
    ]
