# Generated by Django 5.0 on 2025-09-16 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0002_customuser_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_line1', models.CharField(max_length=255)),
                ('add_line2', models.CharField(blank=True, max_length=255)),
                ('add_city', models.CharField(max_length=100)),
                ('add_state', models.CharField(max_length=100)),
                ('add_zip', models.CharField(max_length=10)),
                ('add_type', models.CharField(max_length=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='sim.member')),
            ],
        ),
    ]
