# Generated by Django 5.0 on 2025-09-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0003_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='add_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('School', 'School')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('member', 'add_type'), name='unique_member_address_type'),
        ),
    ]
