# Generated by Django 5.0 on 2025-09-23 16:42

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0004_alter_address_add_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='alt_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('phone_type', models.CharField(choices=[('Mobile', 'Mobile'), ('Home', 'Home'), ('Work', 'Work')], max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='sim.member')),
            ],
        ),
        migrations.AddConstraint(
            model_name='phonenumbers',
            constraint=models.UniqueConstraint(fields=('member', 'phone_type'), name='unique_member_phone_type'),
        ),
    ]
