# Generated by Django 5.0 on 2025-09-26 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0005_remove_customuser_phone_remove_member_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_type', models.CharField(choices=[('activation', 'Account Activation'), ('password_reset', 'Password Reset')], max_length=20)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'token_hash', 'token_type')},
            },
        ),
    ]
