# Generated by Django 5.0 on 2025-09-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0006_usedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumbers',
            name='country_code',
            field=models.CharField(default='+1', max_length=5),
        ),
        migrations.AlterField(
            model_name='phonenumbers',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='phonenumbers',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('member',), name='unique_member_primary_phone'),
        ),
    ]
