# Generated by Django 5.0 on 2025-09-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0007_phonenumbers_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='add_country',
            field=models.CharField(default='United States', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='add_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='add_zip',
            field=models.CharField(max_length=20),
        ),
    ]
