# Generated by Django 5.0 on 2025-09-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0008_address_add_country_alter_address_add_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='add_zip',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
