# Generated by Django 5.0 on 2025-09-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0009_alter_address_add_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateProvince',
            fields=[
                ('st_id', models.IntegerField(primary_key=True, serialize=False)),
                ('st_name', models.CharField(max_length=50)),
                ('st_abbrev', models.CharField(max_length=5)),
                ('st_strtzip', models.CharField(blank=True, max_length=5)),
                ('st_endzip', models.CharField(blank=True, max_length=5)),
                ('st_region', models.CharField(blank=True, max_length=50)),
                ('st_conus', models.BooleanField(default=False)),
                ('st_foreign', models.BooleanField(default=False)),
                ('st_ctrid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'state_province',
                'ordering': ['st_name'],
            },
        ),
    ]
